apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: my-ecr-secret
      containers:
        - name: myapp
          image: 211125762589.dkr.ecr.us-west-2.amazonaws.com/repo:counter_web
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
            - containerPort: 4369  # EPMD
            - containerPort: 9100
            - containerPort: 9101
            - containerPort: 9102
            - containerPort: 9103
            - containerPort: 9104
            - containerPort: 9105
          env:
            - name: ERL_EPMD_PORT
              value: "4369"
            - name: ERL_AFLAGS
              value: "-kernel prevent_overlapping_partitions false inet_dist_listen_min 9100 inet_dist_listen_max 9105"
            - name: MY_COOKIE
              valueFrom:
                secretKeyRef:
                  name: myapp-cookie
                  key: cookie-secret
            - name: MYAPP_NODE_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: node-addresses
                  key: MYAPP_NODE_ADDRESS
            - name: COUNTERNODE_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: node-addresses
                  key: COUNTERNODE_ADDRESS
          command: ["iex"]
          args: ["--name", "$(MYAPP_NODE_ADDRESS)", "--cookie", "$(MY_COOKIE)", "-S", "mix", "phx.server"]