apiVersion: batch/v1
kind: Job
metadata:
  name: clearsettleengine-migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: 211125762589.dkr.ecr.us-west-2.amazonaws.com/repo:clearsettleengine
        command: ["mix", "ecto.migrate"]
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
          - name: DB_DATABSE
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: database
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: db_host
      restartPolicy: Never
  backoffLimit: 4