apiVersion: apps/v1
kind: Deployment
metadata:
  name: clearsettleengine 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clearsettleengine
  template:
    metadata:
      labels:
        app: clearsettleengine
    spec:
      imagePullSecrets:
        - name: my-ecr-secret
      containers:
      - name: clearsettleengine
        image: 211125762589.dkr.ecr.us-west-2.amazonaws.com/repo:clearsettleengine
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: db_host
          - name: DB_DATABSE
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: database
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: db_port
      restartPolicy: Always

