name: Counter Deployment Workflow

# on:
#   repository_dispatch:
#     types: [deploy-clearsettleengine-event]

on:
  workflow_dispatch:
      tags:
        description: 'Test scenario tags'
        
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.24.0'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name my-cluster

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
          
      - name: Pull latest image from Amazon ECR
        run: |
          docker pull 211125762589.dkr.ecr.us-west-2.amazonaws.com/repo:clearsettleengine

      - name: Update deployment image
        run: |
          kubectl apply -f clearsettleengine-deployment.yaml
          kubectl set image deployment/clearsettleengine-deployment clearsettleengine=211125762589.dkr.ecr.us-west-2.amazonaws.com/repo:clearsettleengine

      - name: Run migrations
        working-directory: ./clearsettleengine
        run: |
          kubectl apply -f clearsettleengine-deployment.yaml
          kubectl wait --for=condition=complete job/clearsettleengine-migration

      - name: Restart deployment
        working-directory: ./clearsettleengine
        run: |
          kubectl apply -f clearsettleengine-deployment.yaml
          kubectl rollout restart deployment/clearsettleengine-deployment