on:
  push:
    branches:
      - main
    paths-ignore:
      - 'web/**'
      - 'caddy_docker/**'
      - 'caddy/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update kubeconfig for EKS
      run: aws eks update-kubeconfig --name my-cluster

    - name: Apply ConfigMap
      run: kubectl apply -f configmap.yaml

    - name: Deploy to Kubernetes
      run: kubectl apply -f kube.yaml
      # run: kubectl rollout status deployment/myapp