name: Counter Deployment Workflow

on:
  repository_dispatch:
    types: [deploy-hs-tic-tac-toe-event]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.24.0'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name my-cluster

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true

      - name: Deploy to Kubernetes
        working-directory: ./hs-tic-tac-toe-net
        run: kubectl apply -f main.yaml

      - name: Verify deployment
        working-directory: ./hs-tic-tac-toe-net
        run: kubectl rollout status deployment/tic-tac-toe-deployment